## 추천시스템 개발 코드

**데이터 로딩 및 전처리**

In [1]:
import pandas as pd
data = pd.read_csv('../../lmembers/data/purprod2.csv',encoding='ms949')

In [2]:
data

,제휴사,영수증번호,소분류코드,소분류명,통합분류,소비재분류,고객번호,점포코드,구매일자,구매시간,구매금액,YEAR,월,분기,반기
0,A,1416069,A080106,명품잡화,명품/쥬얼리,전문품,14323,6,20140221,14,101330000,2014,2,Q1,H1
1,A,1500785,A080106,명품잡화,명품/쥬얼리,전문품,14323,6,20140307,14,101110000,2014,3,Q1,H1
2,A,1677262,A080106,명품잡화,명품/쥬얼리,전문품,14323,6,20140405,16,99960000,2014,4,Q2,H1
3,A,4593637,A080110,디자이너,명품/쥬얼리,전문품,13376,1,20150627,16,87769260,2015,6,Q6,H3
4,A,4573361,A080107,명품잡화보석,명품/쥬얼리,전문품,2290,1,20150624,13,74410000,2015,6,Q6,H3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28545420,C,10393540,C170206,종량제봉투,생활잡화,편의품,16122,460,20141203,14,360,2014,12,Q4,H2
28545421,C,6295340,C170206,종량제봉투,생활잡화,편의품,14870,175,20140816,22,360,2014,8,Q3,H2
28545422,C,10193566,C170206,종량제봉투,생활잡화,편의품,6415,417,20141031,12,360,2014,10,Q4,H2
28545423,B,10681400,B210802,재사용봉투,생활잡화,편의품,18782,122,20141122,19,360,2014,11,Q4,H2
28545424,B,10698137,B210802,재사용봉투,생활잡화,편의품,3527,122,20151226,22,360,2015,12,Q8,H4

In [4]:
label_df = pd.read_excel('군집3(target_label=1).xlsx')
label_df

       고객번호  라벨
0         1   0
1         3   2
2         4   0
3         5   1
4        10   2
...     ...  ..
5773  19332   1
5774  19333   2
5775  19334   2
5776  19344   0
5777  19346   2

[5778 rows x 2 columns]

In [5]:
df = pd.merge(label_df,data)

In [7]:
data3 = df.loc[data.구매일자>=20151001]
data6 = df.loc[(data.구매일자<20151001)&(data.구매일자>=20150601)]

In [8]:
cate = pd.read_csv('../../lmembers/data/prodcl2.csv')
data3_cate = pd.merge(data3,cate,on='소분류코드')
data6_cate = pd.merge(data6,cate,on='소분류코드')

In [28]:
data3_cate

,고객번호,라벨,제휴사_x,영수증번호,소분류코드,소분류명_x,통합분류_x,소비재분류_x,점포코드,구매일자,...,분기,반기,제휴사_y,대분류코드,중분류코드,중분류명,소분류명_y,통합분류_y,소비재분류_y,상품분류명
0,1,0,A,5531286,A040222,영 캐릭터,패션의류/잡화,선매품,12,20151120,...,Q8,H4,A,4,402,캐주얼,영 캐릭터,패션의류/잡화,선매품,캐주얼
1,1,0,A,4737696,A040222,영 캐릭터,패션의류/잡화,선매품,12,20150717,...,Q7,H4,A,4,402,캐주얼,영 캐릭터,패션의류/잡화,선매품,캐주얼
2,1,0,A,4122791,A040222,영 캐릭터,패션의류/잡화,선매품,12,20150418,...,Q6,H3,A,4,402,캐주얼,영 캐릭터,패션의류/잡화,선매품,캐주얼
3,73,2,A,2525788,A040222,영 캐릭터,패션의류/잡화,선매품,29,20140812,...,Q3,H2,A,4,402,캐주얼,영 캐릭터,패션의류/잡화,선매품,캐주얼
4,74,0,A,2171946,A040222,영 캐릭터,패션의류/잡화,선매품,2,20140619,...,Q2,H1,A,4,402,캐주얼,영 캐릭터,패션의류/잡화,선매품,캐주얼
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001031,18936,0,C,6987852,C170606,필통,문구,편의품,192,20150304,...,Q5,H3,C,17,1706,문화용품,필통,문구,편의품,문구
1001032,18970,1,B,91697,B070101,마른안주 선물세트,식료품,편의품,4,20140117,...,Q1,H1,B,7,701,선물세트,마른안주 선물세트,식료품,편의품,선물세트
1001033,19148,0,B,6897481,B230503,아동소품,유아동용품,편의품,11,20140827,...,Q3,H2,B,23,2305,아동침구류,아동소품,유아동용품,편의품,아동침구류
1001034,19153,0,B,7593920,B450305,선글라스편집,도서,편의품,18,20150517,...,Q6,H3,B,45,4503,액세서리,선글라스편집,도서,편의품,생활잡화
1001035,19206,0,B,6317725,B090205,페스츄리류,식료품,편의품,6,20140103,...,Q1,H1,B,9,902,베이커리,페스츄리류,식료품,편의품,베이커리

In [30]:
data3_cate.상품분류명[data3_cate.제휴사_x == 'A'].unique()

array(['캐주얼', '주방용품', '주방가전', '트래디셔널', '건강기능식품', '식기', '스카프류', '침구/수예',
       '농산물', '가방', '액세서리', '가공식품', '기초화장품', '생활소형가전', '남성정장', '골프의류',
       '스포츠의류', '정장', '생활잡화', '일반의류', '차/커피', '구두', '수산품', '전자/전기', '양말류',
       '젓갈/반찬', '주류', '색조화장품', '레스토랑', '일용잡화', '기타잡화', '일식', '한식', '위생용품',
       '축산가공', '양식', '디저트', '남성캐주얼', '남성의류', '모자', '소고기', '중식', '카페',
       '문구', '명품', '고급의류', '내의', '골프용품', '모피/피혁', '돼지고기', '기타', '아동',
       '기타육류', '양념육', '닭고기', '가구', '준보석/시계', '분식', '음료', '대형가전', '스포츠잡화',
       '섬유잡화', '신발', '통신/컴퓨터', '홈웨어', '보석', '편의시설', '우산', '아동의류', '기타화장품',
       '악기', '스포츠', '패스트푸드', '여성의류', '기타의류'], dtype=object)

In [31]:
data3_cate.상품분류명[data3_cate.제휴사_x == 'B'].unique()

array(['디저트', '간식', '맛집행사', '피자', '계란', '밥죽류', '라면', '종량제봉투', '서적', '내의',
       '여성캐주얼', '천연조미료', '한방차', '냉장반찬', '양말류', '잡곡', '액세서리', '과채과일', '키위',
       '조리반찬', '감귤', '양념육', '수입기타생선', '견과류', '밤', '두부', '묵/즉석참기름',
       '샐러드/간편채소', '열매채소', '요구르트', '주거세제', '잡곡류', '잎채소', '뿌리채소', '청소용품',
       '조미오징어', '위생용품', '여성위생용품', '멸치', '냉동규격해물', '선어류', '치즈', '간편조리',
       '국산게/갈치', '조명기구', '건과', '바나나', '나물', '음식저장/보관', '수입고등어', '돼지고기',
       '축산가공', '캔디', '샐러드채소', '멸치건명태', '오징어', '유아위생용품', '껌', '인스턴트커피',
       '버섯', '간편채소', '즉석구이김', '조개살', '조개', '해초류', '통조림', '콩나물',
       'LOCAL잎채소', '소스류', '애완용품', '침구/수예', '구강케어', '아이스크림', '냉장식사HMR',
       '식용유지', '욕실용품', '차량용품', '조미김', '우유', '주방세제', '냉장음료', '균일가', '탄산음료',
       '어묵맛살', '스낵', '보수용품', '즉석도정미', '선물세트', '수입소고기', '반건생선', '기초화장품',
       '장류', '포도', '복숭아', '냉동만두', '체리', '맥주', '가공분말류', '양념채소', '딸기',
       '유제품', '냉동가공', '토마토', '감', '해물연체류', '수입포도', '수입감귤과일', '사과', '열대과일',
       '수박', '소주', '시리얼', '버섯류', '떡', '파인애플', '망고', '비스켓', '세탁세제',
       '소금/설탕류', '두유', '면류', '포장반찬', '조미료', '김치채소', '친환경채소', '전통주', '생수',
       '차/커피', '브랜드', '초콜릿', '시즌차', '일반한우', '육가공품', '생선회', '레스토랑',
       '냉동수산물', '골프의류', '차별화돼지고기', '브랜드돼지고기', '아동브랜드', '연체', '커피', '수입연어',
       '냉장규격생선', '기저귀', '젓갈류', '바디케어', '닭고기', '황태', '먹거리행사', '먹거리',
       '친환경과일', '기타회', '분유', '이유식/유아간식', '냉장면류', '주방용품', '특산물', '포장반찬HMR',
       '편의시설', '양념류', 'BABY/INFANT', '유가공', '기능성음료', 'LOCAL김치채소', '기타화장품',
       '남아', '교육보조재', '의류잡화', 'BOYS 저가', '모자', '신발', '스포츠용품', '문구',
       '헤어용품', '빵', '중식', 'SPORTS/OUTDOOR', '냉동간식', '문화용품', '프리미엄과자',
       '건강선물세트', '건강기능식품', '살충제', '헤어케어', '조기/명태', '일반욕실용품', '바디용품',
       '홈웨어', '즉석참기름', '미용티슈', '화장지', '우육', '포도/체리', '전기전자', '수입기타과일',
       '햄소시지', '패브릭욕실용품', '파이', '브랜드빵', '즉석구이안주', '캐주얼', '조리용기', '색조화장품',
       '유아식기', '수예소품', '열대과일기타', '선식', '김가공품', '교육', '와인', '건어류', '마른안주',
       '야외용품', '참외', '종합과자', '복합조미료', '가방', '양곡', '꿀', '반찬류', '김치류',
       '냉장간편식HMR', '배', '잼', '냉동과일', '오렌지과일기타', '야외/시즌용품', '시계', '주유소',
       '족발', '키위/석류', '레몬', '김/초밥', '튀김조리', '수입과자', '냉동HMR', '조리도구', '튀김',
       '수납용품', '남성캐주얼', '남성정장', '소가구', '기타잡화', '간편조리행사', '전통과자', '잡화멀티샵',
       '단무지류', '수입조미', '베이커리', '자몽', '키친타올', '전통간식', '묵', '브랜드한우', '원예용품',
       '블루베리', '석류', '액상조미료', '유아동NPB', 'GIRLS', '예능학용품', '시즌행사', '오리고기',
       '자두', '미역/다시마', '일식', '골프용품', '등산', '수입돼지고기', '스포츠의류', '안주',
       '유/아동서적', '가구', '화장품선물세트', '세탁용품', '우산/양산', '메론', '과채음료', '이온음료',
       '식기', '향신료', '냉동규격생선', '식자재', '전자/전기', '파티/팬시/시즌', '순대', '새우',
       '스포츠잡화', '아동복합샵', '양주', 'EDUCATION 저가', '수입게', '원두커피', '비타민',
       '규격RTC', '남성케어', '섬유유연제', '유아동PB', '오렌지', '생활소형가전', '조미선물세트', '한식',
       '양식', 'Fast Food', '베이비케어', '그릇/수저', '자전거', '수입음료', '수입갈치',
       '미입점행사', '수도용품', '밥류', '마른김', '아동양말', '생활잡화', 'BOYS 고가', '드럭스토어',
       '탈취제', '컨세션', '미용소품', '유아브랜드', '쥐치포', '반찬', '커튼류', '카페', 'TRAVEL',
       '스카프류', '유아동용품', '파티/팬시', '담배', '표백제', '도시락', '아로마', '한우선물세트',
       '인스턴트선물세트', '판매시설', '냉동대용식', '구두', '아동의류', '특산물행사', '커피선물세트', '정장',
       '한과', '벽지류', '여성의류', '휴대폰용품', '장식용품', '이벤트조리', '제습제', '패스트푸드',
       '준보석/시계', '브랜드침구', '통신/컴퓨터', '음반영상', '피트니스', '비디오게임', '국산과일선물세트',
       '유아세제', '분식', '휴지통', '안전용품', '스포츠', '데일리처분', '포장젓갈', '캠핑', '동물병원',
       '약초', '생선초밥', '규격생선선물세트', '대용식', '슈즈용품', '멸치황태미역선물세트', '수입육',
       '열대과일선물세트', '아동침구류', '수입육선물세트', '남성의류', '주방가전', '굴비/반건생선선물세트',
       '기타의류', 'DIY욕실용품', '대형가전', '김선물세트', '주니어웨어', '롤러보드', '기타국소고기',
       '지갑', '유아동특정', '시니어건강용품', '낚시', '마른안주선물세트', '차선물세트', '생선선물세트',
       '주니어스포츠', '기타육류', '브랜드조리', '음식조리', '명품', '오렌지과일선물세트'], dtype=object)

In [32]:
data3_cate.상품분류명[data3_cate.제휴사_x == 'C'].unique()

array(['수입소고기', '과채과일', '생수', '씨리얼', '주방용품', '냉장식사MS', '건어류', '냉장수산',
       '라면', '엽채류', '근채류', '나물류', '청소욕실용품', '선어가공', '소주', '기타수산', '생활잡화',
       '세탁세제', '차/커피', '양곡', '구강케어', '선어류', '견과류', '계란', '위생용품', '과채음료',
       '우유', '김치채소류', '수입과일', '신발', '버섯류', '주방주거세제', '기타조리식품', '건면',
       '발효유', '베이커리', '탄산음료', '두채류', '두유', '건어가공', '양채류', '장류', '케첩마요네즈',
       '냉장음료', '조미료', '간식', '병통조림', '전통주', '기타음주류', '소고기', '냉동과일', '치즈버터',
       '돼지고기', '만두', '해물류', '헤어케어', '잡곡', '반찬류', '냉동MS', '여성위생용품', '식용유',
       '캔디껌류', '냉장기타MS', '닭고기', '냉장농산', '즉석식품', '감미료', '쿠키케이크', '가공분말류',
       '햄소시지', '스낵', '초콜렛', '냉장간식MS', '내의', '기초화장품', '아이스크림', '문구',
       '기능성음료', '유아용품', '커피음료', '맥주', '캠핑', '전통과자', '의류잡화', '식사류', '축산가공',
       '헤어용품', '차량용품', '애완용품', '조명기구', '전기전자', '서적', '통신/컴퓨터', '미용소품',
       '와인', '전자/전기', '수입돼지고기', '분유', '담배', '바디케어', '액세서리', '건강기능식품',
       '양말류', '생활소형가전', '주방가전', '침구/수예', '양주', '비타민', '문화용품', '선식류',
       '색조화장품', '가구', '스포츠', '예능학용품', '교육보조재', '파티/팬시', '원예용품', '스포츠용품',
       '모자', '등산'], dtype=object)

In [9]:
# 상품분류명별 구매횟수를 기준으로 아이템 추천하기 위하여 피벗 생성
pdf3_ori = pd.pivot_table(data3_cate,
                     index = ['고객번호'],              # 행위치에 들어갈 열
                     columns = ['상품분류명'],         # 열위치에 들어갈 열
                     values = ['영수증번호'],              # 데이터로 사용할 열
                     aggfunc = ['count'])         # 데이터 집계 함수
pdf6_ori = pd.pivot_table(data6_cate,
                     index = ['고객번호'],           
                     columns = ['상품분류명'],       
                     values = ['영수증번호'],           
                     aggfunc = ['count'])    
pdf3=pdf3_ori.copy()
pdf6=pdf6_ori.copy()

In [10]:
# Nan값 0으로 대체 및 데이터프레임 정리
pdf3.fillna(0,inplace=True)
pdf3 = pdf3['count']['영수증번호']
pdf6.fillna(0,inplace=True)
pdf6 = pdf6['count']['영수증번호']

### 1. 아이템 기반 최근접 이웃 협업 필터링

In [11]:
pdf3

상품분류명,BABY/INFANT,BOYS 고가,BOYS 저가,DIY욕실용품,EDUCATION 저가,Fast Food,GIRLS,LOCAL김치채소,LOCAL잎채소,SPORTS/OUTDOOR,...,햄소시지,향신료,헤어용품,헤어케어,홈웨어,화장지,화장품선물세트,황태,휴대폰용품,휴지통
고객번호,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19334,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19344,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19346,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
# 코사인유사도는 행기준으로 작동하기에 transpose 함수로 전치
pdf_T = pdf3.transpose()
pdf_T

고객번호,1,3,4,5,10,14,15,18,20,22,...,19314,19317,19323,19325,19327,19332,19333,19334,19344,19346
상품분류명,,,,,,,,,,,,,,,,,,,,,
BABY/INFANT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BOYS 고가,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BOYS 저가,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DIY욕실용품,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EDUCATION 저가,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
화장지,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
화장품선물세트,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
황태,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
휴대폰용품,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
휴지통,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
# 코사인 유사도 산출 (행인 아이템들을 기준으로 사용자간의 유사도)
from sklearn.metrics.pairwise import cosine_similarity
pdf_sim = cosine_similarity(pdf_T, pdf_T)

In [14]:
# cosine_similarity()로 반환된 Numpy 행렬을 중분류명으로 매핑해 DataFrame으로 변환
pdf_sim_df = pd.DataFrame(data=pdf_sim, index=pdf3.columns,
                           columns=pdf3.columns)
print(pdf_sim_df.shape)
pdf_sim_df.head()

(463, 463)

상품분류명,BABY/INFANT,BOYS 고가,BOYS 저가,DIY욕실용품,EDUCATION 저가,Fast Food,GIRLS,LOCAL김치채소,LOCAL잎채소,SPORTS/OUTDOOR,...,햄소시지,향신료,헤어용품,헤어케어,홈웨어,화장지,화장품선물세트,황태,휴대폰용품,휴지통
상품분류명,,,,,,,,,,,,,,,,,,,,,
BABY/INFANT,1.000000,0.186578,0.249992,0.037941,0.243783,0.061081,0.239086,0.008279,0.040983,0.162996,...,0.100606,0.040981,0.057185,0.066693,0.056332,0.035759,0.063567,0.043769,0.034042,0.016429
BOYS 고가,0.186578,1.000000,0.155845,0.074227,0.284356,0.019350,0.167559,0.020247,0.059114,0.085414,...,0.124072,0.028992,0.062418,0.072964,0.031790,0.079895,0.093271,0.062826,0.049949,0.028124
BOYS 저가,0.249992,0.155845,1.000000,0.000000,0.177536,0.026231,0.209882,0.011175,0.026251,0.128854,...,0.071117,0.021730,0.038277,0.042639,0.023394,0.037295,0.047188,0.017979,0.005743,0.029566

In [15]:
pdf_sim_df["화장지"].sort_values(ascending=False)[:6]

상품분류명
화장지        1.000000
미용티슈       0.417070
키친타올       0.372379
음식저장/보관    0.344720
요구르트       0.330013
두부         0.326944
Name: 화장지, dtype: float64

In [16]:
import numpy as np
# 실제 구매횟수와 코사인유사도를 이용하여 개인화된 예측구매횟수를 구함
def predict_rating(ratings_arr, item_sim_arr):
    ratings_pred = ratings_arr.dot(item_sim_arr)/ np.array([np.abs(item_sim_arr).sum(axis=1)])
    return ratings_pred

In [17]:
ratings_pred_knn = predict_rating(pdf3.values , pdf_sim_df.values)
ratings_pred_matrix_knn = pd.DataFrame(data=ratings_pred_knn, index= pdf3.index,
                                   columns = pdf3.columns)
ratings_pred_matrix_knn.head()

상품분류명,BABY/INFANT,BOYS 고가,BOYS 저가,DIY욕실용품,EDUCATION 저가,Fast Food,GIRLS,LOCAL김치채소,LOCAL잎채소,SPORTS/OUTDOOR,...,햄소시지,향신료,헤어용품,헤어케어,홈웨어,화장지,화장품선물세트,황태,휴대폰용품,휴지통
고객번호,,,,,,,,,,,,,,,,,,,,,
1,0.546835,0.426363,0.475531,0.401558,0.587544,0.384763,0.524983,0.324872,0.324391,0.536593,...,0.399731,0.345123,0.424632,0.393618,0.777307,0.382394,0.348071,0.339744,0.333886,0.421160
3,0.331316,0.328237,0.320353,0.390362,0.291995,0.327210,0.398829,0.436310,0.309801,0.315404,...,0.946568,0.329577,0.843981,0.636095,0.325506,0.337593,0.289047,0.310799,0.278432,0.380583
4,0.455613,0.367785,0.420533,0.361000,0.464515,0.370472,0.445799,0.335491,0.338853,0.445272,...,0.393904,0.340045,0.401501,0.376090,0.583481,0.364128,0.325353,0.341379,0.317438,0.373695

In [18]:
from sklearn.metrics import mean_squared_error

# 고객이 구매한 물품에 대해서만 예측 성능 평가 MSE 를 구함. 
def get_mse(pred, actual):
    # Ignore nonzero terms.
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)

print('아이템 기반 모든 인접 이웃 MSE: ', get_mse(ratings_pred_knn, pdf3.values ))

아이템 기반 모든 인접 이웃 MSE:  17.26484781647587

In [19]:
def predict_rating_topsim(ratings_arr, item_sim_arr, n=20):
    # 사용자-아이템 평점 행렬 크기만큼 0으로 채운 예측 행렬 초기화
    pred = np.zeros(ratings_arr.shape)

    # 사용자-아이템 평점 행렬의 열 크기만큼 Loop 수행. 
    for col in range(ratings_arr.shape[1]):
        # 유사도 행렬에서 유사도가 큰 순으로 n개 데이터 행렬의 index 반환
        top_n_items = [np.argsort(item_sim_arr[:, col])[:-n-1:-1]]
        # 개인화된 예측 평점을 계산
        for row in range(ratings_arr.shape[0]):
            pred[row, col] = item_sim_arr[col, :][top_n_items].dot(ratings_arr[row, :][top_n_items].T) 
            pred[row, col] /= np.sum(np.abs(item_sim_arr[col, :][top_n_items]))        
    return pred

In [20]:
ratings_pred_knn = predict_rating_topsim(pdf3.values , pdf_sim_df.values, n=20)
print('아이템 기반 인접 TOP-20 이웃 MSE: ', get_mse(ratings_pred_knn, pdf3.values ))


# 계산된 예측 구매 데이터는 DataFrame으로 재생성
ratings_pred_matrix_knn = pd.DataFrame(data=ratings_pred_knn, index= pdf3.index,
                                   columns = pdf3.columns)

C:\Users\kpo01\AppData\Local\Temp/ipykernel_16444/3564068085.py:11: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row, col] = item_sim_arr[col, :][top_n_items].dot(ratings_arr[row, :][top_n_items].T)
C:\Users\kpo01\AppData\Local\Temp/ipykernel_16444/3564068085.py:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row, col] /= np.sum(np.abs(item_sim_arr[col, :][top_n_items]))

아이템 기반 인접 TOP-20 이웃 MSE:  11.78002741832033

In [21]:
user_rating_id = pdf3.loc[5064, :]
user_rating_id[ user_rating_id > 0].sort_values(ascending=False)[:10]

상품분류명
쿠키케이크    30.0
견과류      14.0
스낵       13.0
과채과일     11.0
생활잡화      8.0
병통조림      8.0
우유        8.0
맥주        8.0
두채류       7.0
엽채류       6.0
Name: 5064, dtype: float64

In [22]:
def get_not_buy_list(ratings_matrix, custid):
    # custid로 입력받은 사용자의 모든 구매정보 추출하여 Series로 반환함. 
    # 반환된 user_rating 은 중분류명을 index로 가지는 Series 객체임. 
    user_rating = ratings_matrix.loc[custid,:]
    
    # user_rating이 0보다 크면 기존에 구매한 물품임. 대상 index를 추출하여 list 객체로 만듬
    already_buy = user_rating[ user_rating > 0].index.tolist()
    
    # 모든 중분류명을 list 객체로 만듬. 
    buy_list = ratings_matrix.columns.tolist()
    
    # 간편한 for문으로 already_buy에 해당하는 물품은 buy_list에서 제외함. 
    notbuy_list = [ item for item in buy_list if item not in already_buy]
    
    return notbuy_list

In [23]:
def recomm_item_by_custid(pred_df, custid, notbuy_list, top_n=10):
    # 구매예측 DataFrame에서 사용자id index와 notbuy_list로 들어온 중분류명 컬럼을 추출하여 가장 예측 구매횟수가 높은 순으로 정렬함. 
    recomm_items = pred_df.loc[custid, notbuy_list].sort_values(ascending=False)[:top_n]
    return recomm_items
    
# 사용자가 구매하지 않은 물품명 추출   
notbuy_list_knn = get_not_buy_list(pdf3, 5064)

# 아이템 기반의 인접 이웃 협업 필터링으로 물품 추천 
recomm_items_knn = recomm_item_by_custid(ratings_pred_matrix_knn, 5064, notbuy_list_knn, top_n=20)

# 구매 데이타를 DataFrame으로 생성. 
recomm_items_knn = pd.DataFrame(data=recomm_items_knn.values,index=recomm_items_knn.index,columns=['pred_score'])
recomm_items_knn

        pred_score
상품분류명
과채음료      5.697319
발효유       5.404868
즉석식품      5.282024
두유        5.216559
냉장음료      5.137210
냉장간식MS    5.124558
치즈버터      5.103541
씨리얼       5.004386
버섯류       4.905137
유아용품      4.776469
냉동MS      4.630593
기타조리식품    4.557653
건어류       4.553246
잡곡        4.283957
양곡        4.260821
전통주       4.223557
냉장기타MS    4.159689
식사류       4.091867
담배        3.926316
장류        3.804608